In [14]:
import numpy as np
import numpy.random as npr

In [15]:
# N - liczba bandytów
N = 10

In [16]:
# Prawdziwe wartości oczekiwane rozładów prawdopodobieństwa
# wygranej dla N maszyn:
prawdziwe_średnie = npr.normal(0, 1, N)

In [17]:
prawdziwe_średnie

array([ 0.3031776 ,  0.20895257, -0.49007015, -0.51370227, -0.31891675,
       -2.81919254, -1.22565719, -1.55843341,  1.36311035, -0.07325882])

In [18]:
# Prawdziwe odchylenia standardowe rozładów prawdopodobieństwa
# wygranej dla N maszyn:
prawdziwe_odst = np.ones(N)
prawdziwe_odst

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
początkowe_zakładane_średnie = npr.normal(0, 1, N)
początkowe_zakładane_średnie

array([ 0.72122196,  1.41626438,  0.91012963, -1.64545764, -1.136286  ,
        0.78740015, -0.85302839, -0.40886658,  0.40411423,  0.19521694])

In [20]:
empiryczne_średnie = początkowe_zakładane_średnie

In [27]:
# Nrozgr - liczba rozgrywek w kasynie = liczba "pociagnięć wajchy"
# jednego z bandytów
Nrozgr = 10
# eps - próg przewagi eksploatacji nad eksploracja
eps = 0.1
# Liczba rozgrywek z każdą z maszyn
lrozgr = np.zeros(N)

In [ ]:
# (x[0] + x[1] + ... + x_[k-1]) / k = S[k]
# x[k]
# S[k+1] = (x[0] + x[1] + ... + x_[k-1] + x[k]) / (k + 1) =
# (x[0] + x[1] + ... + x_[k-1]) / (k + 1) + x_[k] / (k + 1) =
# (x[0] + x[1] + ... + x_{k-1}) / k * (k / (k+1)) + x_[k] / (k + 1) =
# S

In [28]:
całkowita_wygrana = 0
k = 0
llos_tab = npr.uniform(size = Nrozgr)
while k < Nrozgr:
  llos = llos_tab[k]
  if llos > eps:
    index = np.argmax(empiryczne_średnie)
  else:
    index = npr.random_integers(0, N-1)
  print(index)
  lrozgr[index] +=1
  wygrana = npr.normal(prawdziwe_średnie[index], prawdziwe_odst[index])
  całkowita_wygrana + wygrana
# Trzeba zaktualizowac tablice 'empityczne_średnie'
  k +=1
# Narysowac wykres calkowitej wygranej po kazdym kroku

In [30]:
print (całkowita_wygrana)

0
