In [ ]:
import numpy as np
import numpy.random as npr

In [ ]:
# N - liczba bandytów
N = 10

In [ ]:
# Prawdziwe wartości oczekiwane rozkładów prawdopodobieństwa wygranej
# dla N maszyn:
prawdziwe_średnie = npr.normal(0, 1, N)
prawdziwe_średnie

array([ 0.31133002, -0.5546654 , -1.73253463, -1.36614147,  1.78405839,
        0.05424423, -0.02670674, -0.86080847, -0.26512515,  1.75142732])

In [ ]:
# Prawdziwe odchylenia standardowe rozkładów prawdopodobieństwa wygranej
# dla N maszyn:
prawdziwe_odst = np.ones(N)
prawdziwe_odst

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
początkowe_zakładane_średnie = npr.normal(0, 1, N)
początkowe_zakładane_średnie

array([ 1.00836127,  0.2056017 , -0.12940892,  0.81291242, -0.04989559,
        0.72877118,  1.96174245,  2.05274659, -0.89017316,  0.52860173])

In [ ]:
empiryczne_średnie = początkowe_zakładane_średnie

In [ ]:
# Nrozgr - liczba rozgrywek w kasynie = liczba "pociągnięć wajchy" 
# jednego z bandytów
Nrozgr = 10
# eps - próg przewagi eksploatacji nad eksploracją
eps = 0.1
# Liczba rozgrywek z każdą z maszyn
lrozgr = np.zeros(N)

In [ ]:
# (x[0] + x[1] + ... + x[k-1]) / k = S[k]
# x[k]
# S[k+1] = (x[0] + x[1] + ... + x[k-1] + x[k]) / (k + 1) =
# (x[0] + x[1] + ... + x[k-1]) / (k + 1) + x[k] / (k + 1) =
# (x[0] + x[1] + ... + x[k-1]) / k * (k / (k+1)) + x_[k] / (k + 1) =
# S[k] * k / (k + 1) + x[k] / (k+1)

In [ ]:
całkowita_wygrana = 0
k = 0
llos_tab = npr.uniform(size = Nrozgr)
while k < Nrozgr:
  llos = llos_tab[k]
  if llos > eps:
    index = np.argmax(empiryczne_średnie) 
  else:
    index = npr.random_integers(0, N-1)
  print(index)
  lrozgr[index] += 1
  wygrana = npr.normal(prawdziwe_średnie[index], 
                       prawdziwe_odst[index])    
  całkowita_wygrana + wygrana
# Trzeba zaktualizować tablicę 'empiryczne_średnie'. 
  k += 1
# Narysować wygres całkowitej wygranej po każdym kroku.

7
7
7
7
7
7
0
7
7
7


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  if __name__ == '__main__':
